spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      max-active: 50
      initial-size: 1
      min-idle: 10
      max-wait: 60000
      validation-query: select 1 from dual
      validation-query-timeout: 5
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j2
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-password: demo
        login-username: demo
      http:
        encoding:
          force: true
          charset: UTF-8
          enabled: true
      server:
        tomcat:
          uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml